console.log('Ejecutando el Sistema')
console.log('Validación Control de Versiones')
console.log('Adición Cambio desde GIT HUB directamente')
console.log('Adición Cambio desde VISUAL DE GIT HUB directamente')
console.log('Adición Cambio desde VISUAL DE GIT HUB directamente 2')
console.log('Adición Cambio desde VS Code en F1  Open Repository ')